name: Formatting
on: [push, pull_request]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Black Code Formatter Check
        uses: lgeiger/black-action@master
        with:
          args: "--line-length 120 . --check"

  auto-formatting:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "--line-length 120 ."
